// アクションのタイプ
export const ADD_FOLDERANDNOTE = 'ADD_FOLDERANDNOTE';
export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTEINFOLDER = 'UPDATE_NOTEINFOLDER';
